---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: suilens-2206811474
spec:
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30173
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: suilens-2206811474
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: suilens-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_CATALOG_API
          value: "http://catalog-service:3001"
        - name: VITE_ORDER_API
          value: "http://order-service:3002"
        - name: VITE_NOTIFICATION_API
          value: "http://notification-service:3003"