apiVersion: v1
kind: Secret
metadata:
  name: suilens-secrets
  namespace: suilens-2206811474
type: Opaque
stringData:
  CATALOG_DB_USER: catalog
  CATALOG_DB_PASSWORD: catalog
  ORDER_DB_USER: orders
  ORDER_DB_PASSWORD: orders
  NOTIFICATION_DB_USER: notifications
  NOTIFICATION_DB_PASSWORD: notifications
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest